name: test_if

on:
  push:
    branches:
      - dev
      - release
      - test_if
  pull_request:
    branches:
      - dev
      - release
      - test_if
    paths:
      - .github/workflows/pypi.yml
      - build_scripts/pypi/*.py
      - build_scripts/pypi/package_files/*
  workflow_dispatch:
    inputs:
      post_release_tag:
        description: 'post release tag'
        default: ''
  issue_comment:
    types: [created]

env:
  POST_RELEASE_TAG: ${{ github.event.inputs.post_release_tag == '' && ' ' || format('--post-release-tag {0}', github.event.inputs.post_release_tag) }}
jobs:
  Linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    # if: (${{ github.event_name == 'issue_comment' }} && contains(github.event.comment.html_url, '/accepted')) ||  ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }}
    # if: ${{ github.event_name == 'issue_comment' }} || ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }}
    if: contains(github.event.comment.body, '/accepted')   # check the comment if it contains the keywords
      run: |
        echo say hello
